### ISSUE TITLE
AttributeError: 'WikipediaService' object has no attribute '_conn'

### ISSUE THREAD

**Issue by ralf-berger** [ude-soco/CourseMapper-webserver#1075]
After fixing #1058, I'm getting the following errors from `coursemapper-kg-concept-map` on startup:

```
bin/worker: Running application ...
Traceback (most recent call last):
  File "/home/app/src/main.py", line 16, in <module>
    concept_map_pipeline = ConceptMapPipeline()
                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/app/src/pipelines/concept_map.py", line 23, in __init__
    self.wikipedia_service = WikipediaService()
                             ^^^^^^^^^^^^^^^^^^
  File "/home/app/src/services/wikipedia.py", line 29, in __init__
    self._conn = psycopg.connect(Config.WIKIPEDIA_DATABASE_CONNECTION_STRING, row_factory=dict_row)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/.venv/lib/python3.11/site-packages/psycopg/connection.py", line 98, in connect
    attempts = conninfo_attempts(params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/.venv/lib/python3.11/site-packages/psycopg/_conninfo_attempts.py", line 50, in conninfo_attempts
    raise e.OperationalError(str(last_exc))
psycopg.OperationalError: [Errno -2] Name or service not known
Exception ignored in: <function WikipediaService.__del__ at 0x7f637db29bc0>
Traceback (most recent call last):
  File "/home/app/src/services/wikipedia.py", line 35, in __del__
AttributeError: 'WikipediaService' object has no attribute '_conn'
```

**Comment by rawaa123** [comment]
we still facing the same issue:

```
bin/worker: Running application ...
Traceback (most recent call last):
  File "/home/app/src/main.py", line 16, in <module>
    concept_map_pipeline = ConceptMapPipeline()
                           ^^^^^^^^^^^^^^^^^^^^
  File "/home/app/src/pipelines/concept_map.py", line 23, in __init__
    self.wikipedia_service = WikipediaService()
                             ^^^^^^^^^^^^^^^^^^
  File "/home/app/src/services/wikipedia.py", line 29, in __init__
    self._conn = psycopg.connect(Config.WIKIPEDIA_DATABASE_CONNECTION_STRING, row_factory=dict_row)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/app/.venv/lib/python3.11/site-packages/psycopg/connection.py", line 119, in connect
    raise last_ex.with_traceback(None)
**psycopg.OperationalError: connection failed: connection to server at "10.43.171.86", port 5432 failed: server closed the connection unexpectedly**
	This probably means the server terminated abnormally
	before or while processing the request.
Exception ignored in: <function WikipediaService.__del__ at 0x7f2269c21bc0>
Traceback (most recent call last):
  File "/home/app/src/services/wikipedia.py", line 35, in __del__
AttributeError: 'WikipediaService' object has no attribute '_conn'
```
