### ISSUE TITLE
Human-in-the-loop approach - Error in KG Expansion

### ISSUE THREAD

**Issue by qurat08** [ude-soco/CourseMapper-webserver#982]
KG expansion stopped with an error
![image](https://github.com/user-attachments/assets/d71f8baf-77d6-4caa-869f-678b0f519007)

```
Logs: 
2024-07-31 20:06:31 [436272] 5861b55c3a9c4cfcd5a1636ae6454474a305e89e04bc679653a1c0184d307a13: Expanding 26 concepts
2024-07-31 20:08:38 [436272] 5861b55c3a9c4cfcd5a1636ae6454474a305e89e04bc679653a1c0184d307a13: CourseMapper Worker: Error processing expand-material job 5861b55c3a9c4cfcd5a1636ae6454474a305e89e04bc679653a1c0184d307a13
2024-07-31 20:08:38 [436272] 5861b55c3a9c4cfcd5a1636ae6454474a305e89e04bc679653a1c0184d307a13: Traceback (most recent call last):
  File "C:\Users\Qurat Ul Ain\.virtualenvs\concept-map-jBCa8O8L\Lib\site-packages\urllib3\connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Qurat Ul Ain\.virtualenvs\concept-map-jBCa8O8L\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\Qurat Ul Ain\.virtualenvs\concept-map-jBCa8O8L\Lib\site-packages\urllib3\connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Qurat Ul Ain\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1378, in getresponse
    response.begin()
  File "C:\Users\Qurat Ul Ain\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Qurat Ul Ain\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Qurat Ul Ain\.virtualenvs\concept-map-jBCa8O8L\Lib\site-packages\requests\adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Qurat Ul Ain\.virtualenvs\concept-map-jBCa8O8L\Lib\site-packages\urllib3\connectionpool.py", line 801, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Qurat Ul Ain\.virtualenvs\concept-map-jBCa8O8L\Lib\site-packages\urllib3\util\retry.py", line 552, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Qurat Ul Ain\.virtualenvs\concept-map-jBCa8O8L\Lib\site-packages\urllib3\packages\six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Qurat Ul Ain\.virtualenvs\concept-map-jBCa8O8L\Lib\site-packages\urllib3\connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Qurat Ul Ain\.virtualenvs\concept-map-jBCa8O8L\Lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\Qurat Ul Ain\.virtualenvs\concept-map-jBCa8O8L\Lib\site-packages\urllib3\connectionpool.py", line 462, in _make_request
    httplib_response = conn.getresponse()
                       ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Qurat Ul Ain\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 1378, in getresponse
    response.begin()
  File "C:\Users\Qurat Ul Ain\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Qurat Ul Ain\AppData\Local\Programs\Python\Python311\Lib\http\client.py", line 287, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Qurat Ul Ain\.virtualenvs\concept-map-jBCa8O8L\Lib\site-packages\cm_worker\worker.py", line 188, in start
    result = self._pipelines[pipeline](job)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Qurat Ul Ain\Documents\GitHub\CourseMapper-webserver\coursemapper-kg\concept-map\src\main.py", line 38, in execute_expand_material_job
    expand_material_pipeline.run(worker.push_log_message, job.get('materialId'))
  File "C:\Users\Qurat Ul Ain\Documents\GitHub\CourseMapper-webserver\coursemapper-kg\concept-map\src\pipelines\expand_material.py", line 25, in run
    self.expand_material_graph(graph, push_log_message)
  File "C:\Users\Qurat Ul Ain\Documents\GitHub\CourseMapper-webserver\coursemapper-kg\concept-map\src\pipelines\expand_material.py", line 136, in expand_material_graph
    expanded_concept_embeddings = self._wikipedia_service.get_page_embeddings(self._embedding_service, expansion_df['title'].to_list(), 'page')
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Qurat Ul Ain\Documents\GitHub\CourseMapper-webserver\coursemapper-kg\concept-map\src\services\wikipedia.py", line 136, in get_page_embeddings
    missing_page = self.get_page(title)
                   ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Qurat Ul Ain\Documents\GitHub\CourseMapper-webserver\coursemapper-kg\concept-map\src\services\wikipedia.py", line 68, in get_page
    return WikipediaPage(page.title, page.summary, [category_name for _, category_name in page_categories], page_links)
                                     ^^^^^^^^^^^^
  File "C:\Users\Qurat Ul Ain\.virtualenvs\concept-map-jBCa8O8L\Lib\site-packages\wikipediaapi\__init__.py", line 920, in summary
    self._fetch("extracts")
  File "C:\Users\Qurat Ul Ain\.virtualenvs\concept-map-jBCa8O8L\Lib\site-packages\wikipediaapi\__init__.py", line 1064, in _fetch
    getattr(self.wiki, call)(self)
  File "C:\Users\Qurat Ul Ain\.virtualenvs\concept-map-jBCa8O8L\Lib\site-packages\wikipediaapi\__init__.py", line 297, in extracts
    raw = self._query(page, used_params)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Qurat Ul Ain\.virtualenvs\concept-map-jBCa8O8L\Lib\site-packages\wikipediaapi\__init__.py", line 528, in _query
    r = self._session.get(base_url, params=params, **self._request_kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Qurat Ul Ain\.virtualenvs\concept-map-jBCa8O8L\Lib\site-packages\requests\sessions.py", line 602, in get
    return self.request("GET", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Qurat Ul Ain\.virtualenvs\concept-map-jBCa8O8L\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Qurat Ul Ain\.virtualenvs\concept-map-jBCa8O8L\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Qurat Ul Ain\.virtualenvs\concept-map-jBCa8O8L\Lib\site-packages\requests\adapters.py", line 682, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
Traceback (most recent call last):

  File "C:\Users\Qurat Ul Ain\Documents\GitHub\CourseMapper-webserver\coursemapper-kg\concept-map\src\main.py", line 45, in <module>
2024-07-31 20:08:38 [436272] 5861b55c3a9c4cfcd5a1636ae6454474a305e89e04bc679653a1c0184d307a13: CourseMapper Worker: Received concept-map job for 5861b55c3a9c4cfcd5a1636ae6454474a305e89e04bc679653a1c0184d307a13...
    worker.start()
  File "C:\Users\Qurat Ul Ain\.virtualenvs\concept-map-jBCa8O8L\Lib\site-packages\cm_worker\worker.py", line 173, in start
    assert(type(job) == bytes)
           ^^^^^^^^^^^^^^^^^^
AssertionError

C:\Users\Qurat Ul Ain\Documents\GitHub\CourseMapper-webserver\coursemapper-kg\concept-map>

```

**Comment by qurat08** [comment]
expansion is working fine now
